# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [5]:
arr= np.random.randint(1,21 ,size=(5,5))
print(arr)

[[ 8 17  3  8  2]
 [16  7  4 10 10]
 [12  9 15  5  6]
 [20  6 12 11  4]
 [ 5 10 15 13 12]]


In [6]:
arr[:,2]= 1
print(arr)

[[ 8 17  1  8  2]
 [16  7  1 10 10]
 [12  9  1  5  6]
 [20  6  1 11  4]
 [ 5 10  1 13 12]]


In [8]:
arr1= np.arange(1,17).reshape(4,4)
print(arr1)
np.fill_diagonal(arr1,0)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [10]:
arr2= np.arange(1,37).reshape(6,6)
subarr= arr2[2:5,1:4]
print(arr2)
print(subarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [11]:
a= np.random.randint(1,21, size =(5,5))
print(a)
print("Border elements")
border_elements= np.concatenate((a[0,:],a[-1,:], a[1:-1,0], a[1:-1,4]))
print(border_elements)

[[ 3  7  4 12 14]
 [ 8 20 17 13  8]
 [ 5  1  7  1 19]
 [ 9 13  2 19 19]
 [ 7 19  9 19  7]]
Border elements
[ 3  7  4 12 14  7 19  9 19  7  8  5  9  8 19 19]


In [14]:
a1= np.random.randint(1,13,  size= (3,4))
print(a1)
a2= np.random.randint(1,13,  size= (3,4))
print(a2)

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[[ 3 12  6  9]
 [11 11  5 11]
 [ 6  7  4  1]]
[[ 1  7 11  4]
 [10 10  3  9]
 [10 11  7  9]]
[[ 4 19 17 13]
 [21 21  8 20]
 [16 18 11 10]]
[[ 2  5 -5  5]
 [ 1  1  2  2]
 [-4 -4 -3 -8]]
[[  3  84  66  36]
 [110 110  15  99]
 [ 60  77  28   9]]
[[3.         1.71428571 0.54545455 2.25      ]
 [1.1        1.1        1.66666667 1.22222222]
 [0.6        0.63636364 0.57142857 0.11111111]]


In [16]:
a= np.arange(1,17).reshape(4,4)
row_sum= np.sum(a,axis=0)
column_sum= np.sum(a,axis=1)
print(a)
print(row_sum)
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40]
[10 26 42 58]


In [17]:
a= np.random.randint(1,21, size=(5,5))
print(a)
mean= np.mean(a)
median= np.median(a)
std_dev= np.std(a)
variance= np.var(a)
print(mean,median,std_dev,variance)

[[11 16  8  5 12]
 [ 3  2  1 18 10]
 [ 2 11  8  8  6]
 [ 8 14  8  6 15]
 [13  9  6 11 13]]
8.96 8.0 4.431523440082429 19.6384


In [18]:
a1= np.arange(1,10).reshape(3,3)
print(a1)
mean= np.mean(a1)
std_dev=np.std(a1)
normalization= (a1-mean)/std_dev
print(normalization)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [19]:
a= np.random.randint(1,11 , size= (3,3))
b= np.random.randint(1,11 , size= (3,))

print(a)
print(b)
new= a+b
print(new)

[[ 5  5  1]
 [10 10  2]
 [ 4  9  2]]
[4 7 8]
[[ 9 12  9]
 [14 17 10]
 [ 8 16 10]]


In [20]:
a= np.random.randint(1,11 , size= (4,4))
b= np.random.randint(1,11 , size= (4,))
print(a)
print(b)
new= a-b
print(new)

[[ 3  6  9  3]
 [ 1  7  9 10]
 [ 2  6  6  8]
 [ 5  7  4  4]]
[ 1 10 10 10]
[[ 2 -4 -1 -7]
 [ 0 -3 -1  0]
 [ 1 -4 -4 -2]
 [ 4 -3 -6 -6]]


In [21]:
a= np.random.randint(1,11 , size= (3,3))
det= np.linalg.det(a)
inv= np.linalg.inv(a)
eig= np.linalg.eigvals(a)
print(det)
print(inv)
print(eig)

-133.0
[[-0.02255639 -0.10526316  0.2406015 ]
 [-0.01503759  0.26315789 -0.17293233]
 [ 0.19548872 -0.42105263  0.2481203 ]]
[13.16893742 -5.88506522  1.7161278 ]


In [22]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

matrix_product= np.dot(array1,array2)
print(matrix_product)

Array 1:
[[10  3  1]
 [ 3  6  8]]
Array 2:
[[ 6  3]
 [10  7]
 [ 6  1]]
[[ 96  52]
 [126  59]]


In [24]:
a= np.arange(1,10).reshape(3,3)
b= a.reshape(1,9)
c= a.reshape(9,1)
print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [26]:
array = np.random.randint(1, 21, size=(5, 5))
flatten= array.flatten()
print(array)
print(flatten)
reshaped_array = flatten.reshape((5, 5))
print(reshaped_array)

[[14 18 10  3 13]
 [ 7  1  2 12 11]
 [ 1 17  8  8  3]
 [ 8 16  7 19 17]
 [16  6 12 19 17]]
[14 18 10  3 13  7  1  2 12 11  1 17  8  8  3  8 16  7 19 17 16  6 12 19
 17]
[[14 18 10  3 13]
 [ 7  1  2 12 11]
 [ 1 17  8  8  3]
 [ 8 16  7 19 17]
 [16  6 12 19 17]]


In [27]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)

corners= array[[0, 0, -1, -1], [0, -1, 0, -1]]
print(corners)

[[ 3 16 13 16 18]
 [ 5 20 12  6 16]
 [16 10 17  8 19]
 [10 12  9  9 13]
 [ 6 18 13  6 15]]
[ 3 18  6 15]


In [29]:
array = np.random.randint(1, 21, size=(4, 4))
print(array)
array[array>10]=10
print(array)

[[ 4 16 10 10]
 [19 11 10 13]
 [10 13  4 13]
 [15  1 14 15]]
[[ 4 10 10 10]
 [10 10 10 10]
 [10 10  4 10]
 [10  1 10 10]]


In [2]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
a= np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype= data_type)
print(a)

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


In [8]:
data_type= [('x', 'i4'), ('y','i4')]
a= np.array([(1,2),(3,4)], dtype= data_type)
print(a)

dist= np.sqrt((a['x'][:, np.newaxis]- a['x'])**2+ (a['y']- a['y'])**2)
print(dist)

[(1, 2) (3, 4)]
[[0. 2.]
 [2. 0.]]
